apiVersion: v1    
kind: Secret
metadata:
  name: jwt-secret  
  namespace: chat-app
type: Opaque
data:
  JWT_SECRET: OTcyMGMxZmI2ZWY5MmRmOTczMGM4NDljMzc2ODEwZTMyNzU5NWExMjkyY2Y1YWRiZmM2YTUxZmFjOWQzMjc0OTBiOGU5c1g1YjJmN2Q3Zjk3
  